// Generated by CoffeeScript 1.4.0
(function() {
  var subdir, subdirs, _i, _len;

  subdirs = document.getElementsByClassName('subdir');

  for (_i = 0, _len = subdirs.length; _i < _len; _i++) {
    subdir = subdirs[_i];
    subdir.addEventListener('click', function() {
      return this.getElementsByTagName('ul')[0].style.display = 'block';
    });
  }

}).call(this);
